package lexer;
 
/**
 *  This file is automatically generated<br>
 *  - it contains the enumeration of all of the tokens
*/
public enum Tokens {
  BogusToken,Program,Int,BOOLean,Float,
    If,Then,Else,While,Repeat,
    Function,Return,Identifier,INTEGER,FLOAT,
    LeftBrace,RightBrace,LeftParen,RightParen,Comma,
    Assign,Equal,NotEqual,Less,LessEqual,
    Plus,Minus,Or,And,Multiply,
    Divide,Comment
}
